DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS films_genre CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS likes CASCADE;

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id INTEGER NOT NULL AUTO_INCREMENT,
    rating varchar NOT NULL,
    CONSTRAINT MPA_PK PRIMARY KEY (mpa_id)
);


CREATE TABLE IF NOT EXISTS films
(
    film_id      INTEGER NOT NULL AUTO_INCREMENT,
    name         varchar NOT NULL,
    description  varchar(200),
    release_date TIMESTAMP,
    duration     INTEGER,
    mpa_id       INTEGER NOT NULL,
    CONSTRAINT FILMS_PK PRIMARY KEY (film_id),
    CONSTRAINT FILMS_FK FOREIGN KEY (mpa_id) REFERENCES mpa (mpa_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);


CREATE TABLE IF NOT EXISTS genres
(
    genre_id INTEGER NOT NULL AUTO_INCREMENT,
    name     varchar NOT NULL,
    CONSTRAINT GENRES_PK PRIMARY KEY (genre_id)
);

CREATE TABLE IF NOT EXISTS films_genre
(
    id       INTEGER NOT NULL AUTO_INCREMENT,
    film_id  INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    CONSTRAINT FILMS_GENRE_PK PRIMARY KEY (id),
    CONSTRAINT FILMS_GENRE_FK FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT FILMS_GENRE_FK_1 FOREIGN KEY (genre_id) REFERENCES genres (genre_id) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS users
(
    user_id  INTEGER     NOT NULL AUTO_INCREMENT,
    login    varchar     NOT NULL,
    name     varchar,
    birthday TIMESTAMP   NOT NULL,
    email    varchar(25) NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    id        INTEGER NOT NULL AUTO_INCREMENT,
    user_id   INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    CONSTRAINT FRIENDS_PK PRIMARY KEY (id),
    CONSTRAINT FRIENDS_FK FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT FRIENDS_FK_1 FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE RESTRICT
);


CREATE TABLE IF NOT EXISTS likes
(
    like_id INTEGER NOT NULL AUTO_INCREMENT,
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT LIKES_PK PRIMARY KEY (like_id),
    CONSTRAINT LIKES_FK FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT LIKES_FK_1 FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE RESTRICT
);